test: Move `Coin` `==` operator out of anon namespace
The lookup for `==` is unqualified with Boost.Test, but when doing the
`==` lookup in the later migration commit this causes a compiler error
as the `==` is being looked up outside of the namespace within
`framework.h`:

```
In file included from /home/rob/bitcoin-core/bitcoin/src/test/coins_tests.cpp:26:
/home/rob/bitcoin-core/bitcoin/src/test/util/framework.h:417:18: error: invalid operands to binary expression ('const Coin' and 'const Coin')
  417 |     DECOMPOSE_OP(==, std::cmp_equal)
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/rob/bitcoin-core/bitcoin/src/test/util/framework.h:411:57: note: expanded from macro 'DECOMPOSE_OP'
  411 |                 btc_test_result = static_cast<bool>(lhs op rhs);                                                   \
      |                                                     ~~~ ^  ~~~
/home/rob/bitcoin-core/bitcoin/src/test/coins_tests.cpp:177:30: note: in instantiation of function template specialization 'framework::CapturedExpression<Coin>::operator==<Coin>' requested here
  177 |             BOOST_CHECK(coin == entry);
      |                              ^
/home/rob/bitcoin-core/bitcoin/src/support/allocators/pool.h:350:6: note: candidate template ignored: could not match 'const PoolAllocator<T1, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES>' against 'const Coin'
  350 | bool operator==(const PoolAllocator<T1, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES>& a,
      |      ^
/home/rob/bitcoin-core/bitcoin/src/support/allocators/pool.h:350:6: note: candidate template ignored: could not match 'const PoolAllocator<T1, MAX_BLOCK_SIZE_BYTES, ALIGN_BYTES>' against 'const Coin'
```